In [33]:
import pandas as pd
import numpy as np
import json
import joblib
import os
from pathlib import Path
from typing import List, Dict, Any, Optional
from tqdm.auto import tqdm
from pypdf import PdfReader
from dotenv import load_dotenv

# Langhchain framework
from langchain_core.documents import Document
from langchain_classic.text_splitter import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

# HF + Groq clients
from huggingface_hub import InferenceClient
from groq import Groq

import warnings
warnings.filterwarnings("ignore")

pd.set_option('display.max_columns', None)

## Load API keys for credential key

In [34]:
ENV_PATH = Path.cwd().parent.parent / "credit_risk_production" / ".env"
load_dotenv(dotenv_path=ENV_PATH)

HUGGINGFACE_API_KEY = os.getenv("HUGGINGFACE_API_KEY")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
NINEROUTER_API_KEY = os.getenv("NINEROUTER_API_KEY")
NINEROUTER_BASE_URL = os.getenv("NINEROUTER_BASE_URL")

print(f"HF token loaded:  {HUGGINGFACE_API_KEY[:3]}...")
print(f"GROQ token loaded: {GROQ_API_KEY[:3]}...")
print(f"NR token loaded:  {NINEROUTER_API_KEY[:3]}...")
print(f"NR base URL:     {NINEROUTER_BASE_URL[:3]}...")

HF token loaded:  hf_...
GROQ token loaded: gsk...
NR token loaded:  sk-...
NR base URL:     htt...

## Load database

In [35]:
DATA = Path.cwd().parent.parent / "credit_risk_production" / "database" / "data" / "merged_credit_risk_data_with_fraud.parquet"
FEATURES = Path.cwd().parent.parent / "credit_risk_production" / "database" / "data" / "features_data.parquet"

df = pd.read_parquet(DATA)
features = pd.read_parquet(FEATURES)

print(f"Data loaded: {df.shape[0]} rows, {df.shape[1]} columns")
print(f"Features loaded: {features.shape[0]} rows, {features.shape[1]} columns")

Data loaded: 51336 rows, 88 columns
Features loaded: 51336 rows, 47 columns

## Load Fraud ML Models

In [36]:
# Load ML models from bundle
MODEL_BUNDLE = Path.cwd().parent.parent / "data_science" / "models" / "fraud_models" / "model_bundle.joblib"
with open(MODEL_BUNDLE, "rb") as f:
    model_bundle = joblib.load(f)
    print(f"Model bundle loaded: {list(model_bundle.keys())}")

# Load best parameters for each model
PARAMS = Path.cwd().parent.parent / "data_science" / "models" / "metrics" / "best_parameters.json"
with open(PARAMS, "r") as f:
    best_params = json.load(f)
    print(f"Best parameters loaded: {list(best_params.keys())}")

# Load metrics model
METRICS = Path.cwd().parent.parent / "data_science" / "models" / "metrics" / "model_metrics.csv"
metrics_df = pd.read_csv(METRICS)
display(metrics_df)

Model bundle loaded: ['models', 'scaler', 'label_encoders', 'feature_columns', 'class_labels']
Best parameters loaded: ['Logistic Regression', 'Random Forest', 'Decision Tree', 'XGBoost', 'K-Nearest Neighbors']

                 Model  Accuracy  Precision    Recall  F1 Score   ROC AUC
0  Logistic Regression  0.957148   0.955984  0.988137  0.971795  0.958286
1        Random Forest  0.982859   0.986372  0.990744  0.988554  0.998319
2        Decision Tree  0.986560   0.995266  0.986703  0.990966  0.993473
3              XGBoost  0.987924   0.998547  0.985269  0.991864  0.998564
4  K-Nearest Neighbors  0.869108   0.885370  0.947464  0.915365  0.906852

# 📚 Document Ingestion — PDF → Chunks (per-document strategy)

In [37]:
PDF_DIR = Path("../../credit_risk_production/database/pdf")

pdf_files = {
    "delinquency":  PDF_DIR / "Delinquency_Classification .pdf",
    "fraud":        PDF_DIR / "Fraud_Typologies_and_Red Flags .pdf",
    "regulatory":   PDF_DIR / "Regulatory_Risk Policy Core .pdf",
    "scorecard":    PDF_DIR / "Scorecard_Cut-off Policy.pdf"
}

raw_texts: Dict[str, str] = {}

for name, path in pdf_files.items():
    reader = PdfReader(str(path))
    text = "\n".join((page.extract_text() or "") for page in reader.pages)
    raw_texts[name] = text
    print(f"{name:12s} | pages={len(reader.pages):3d} | chars={len(text):,}")

delinquency  | pages= 93 | chars=191,238
fraud        | pages=  9 | chars=25,113
regulatory   | pages= 11 | chars=34,419
scorecard    | pages=178 | chars=465,508

## Chunking strategy to retrieve Document augmentation for each PDFs to enrich vocab on LLM
- #### Strategy 1: Delinquency Classification — rule-based chunking
- #### Strategy 2: Fraud Typologies — focusing on fraud paragraph to be chunked
- #### Strategy 3: Regulatory Policy — recursive with heading preservation
- #### Strategy 4: Scorecard Cut-off — table-aware chunking
- #### Final Strategy: Combine all chunks

In [38]:
def chunk_delinquency(text: str) -> List[Document]:
    """Split by classification headings, falls back to paragraph split."""
    keywords = ["Standard", "Sub-standard", "Substandrad", "Doubtful", "Loss"]

    # Crude split: find the index of each keyword and slice
    positions = []
    for kw in keywords:
        idx = text.lower().find(kw.lower())
        if idx != -1:
            positions.append((idx, kw))
    positions.sort()

    docs: List[Document] = []
    if not positions:

        splitter = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=100)
        for i, chunk in enumerate(splitter.split_text(text)):
            docs.append(Document(
                page_content=chunk,
                metadata={"doc_type": "delinquency", "chunk_id": i, "class_level": "unknown"}
            ))
        return docs

    for i, (start, kw) in enumerate(positions):
        end = positions[i + 1][0] if i + 1 < len(positions) else len(text)
        chunk = text[start:end].strip()

        if len(chunk) < 30:
            continue

        docs.append(Document(
            page_content=chunk,
            metadata={"doc_type": "delinquency", "class_level": kw.lower(), "chunk_id": i},
        ))

    return docs

# Usage on delinquency PDF
deling_docs = chunk_delinquency(raw_texts["delinquency"])
print(f"Delinquency chunks: {len(deling_docs)}")
print(deling_docs[3].page_content[:300], "\n--")

Delinquency chunks: 4
sub-standard' immediately on restructuring,
all borrowers, with the exception of the borrowal categories specified in para 14.1 below ( i.e
consumer and personal advances, advances classified as capital market and real estate
exposures), will be entitled to retain the asset classification upon re
--

#### Strategy 2: Fraud Typologies — focusing on fraud paragraph to be chunked

In [39]:
def chunk_fraud(text: str) -> List[Document]:
    """Split by typology headings, falls back to paragraph split."""
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=800, 
        chunk_overlap=80,
        separators=["\n\n\n", "\n\n", "\n", ". ", " "]
    )
    docs = []
    for i, chunk in enumerate(splitter.split_text(text)):
        docs.append(Document(
            page_content=chunk,
            metadata={"doc_type": "fraud", "chunk_id": i, "typology": "unspecified"}
        ))
    return docs

# Usage on fraud PDF
fraud_docs = chunk_fraud(raw_texts["fraud"])
print(f"Fraud chunks: {len(fraud_docs)}")
print(fraud_docs[3].page_content[:300], "\n--")

Fraud chunks: 36
platforms achieved a 61% improvement in detection accuracy, 48% reduction in false positives, and 72% faster
investigation turnaround. The project management model introduced in this article outlines the lifecycle for planning,
building, validating, deploying, and governing these systems, emphasiz
--

### Strategy 3: Regulatory Policy — recursive with heading preservation

In [40]:
def chunk_regulatory(text: str) -> List[Document]:
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=800, 
        chunk_overlap=120,
        separators=["\n\n", "\n", ". ", " "]
    )
    docs = []
    for i, chunk in enumerate(splitter.split_text(text)):
        docs.append(Document(
            page_content=chunk,
            metadata={"doc_type": "regulatory", "chunk_id": i},
        ))
    return docs

# Usage on regulatory PDF
regulatory_docs = chunk_regulatory(raw_texts["regulatory"])
print(f"Regulatory chunks: {len(regulatory_docs)}")
print(regulatory_docs[1].page_content[:411], "\n--")

Regulatory chunks: 53
(FPC). However, despite these guidelines, rising consumer complaints indicate a gap between regulatory
expectations and actual practices. This study aims to empirically examine the compliance of FPC norms among
Banks and Housing Finance Companies (HFCs), as perceived by lending officials and borrowers. Primary data
were collected from 294 borrowers and 102 lending branches using structured questionnaires.
--

### Strategy 4: Scorecard Cut-off — table-aware chunking

In [41]:
import re

def chunk_scorecard(text: str) -> List[Document]:
    """Detect numeric ranges like 700-750 or 700 - 750 and split accordingly."""
    pattern = re.compile(r"(\d{3})\s*[--to]+\s*(\d{3})")
    matches = list(pattern.finditer(text))

    docs: List[Document] = []
    if not matches:
        splitter = RecursiveCharacterTextSplitter(
            chunk_size=700, 
            chunk_overlap=80,
            separators=["\n\n", "\n", ". ", " "]
        )
        for i, chunk in enumerate(splitter.split_text(text)):
            docs.append(Document(
                page_content=chunk,
                metadata={"doc_type": "scorecard", "chunk_id": i, "min_score": None, "max_score": None}
            ))
        return docs

    for i, m in enumerate(matches):
        start = m.start()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        chunk = text[start:end].strip()

        if len(chunk) < 30:
            continue
        docs.append(Document(
            page_content=chunk,
            metadata={
                "doc_type": "scorecard",
                "chunk_id": i,
                "min_score": int(m.group(1)),
                "max_score": int(m.group(2))
            }
        ))
    return docs

# Usage on scorecard PDF
score_docs = chunk_scorecard(raw_texts["scorecard"])
print(f"Scorecard chunks: {len(score_docs)}")
print(score_docs[1].page_content[:300], "\n--")

Scorecard chunks: 12
300 to 850.

Credit bureau scores consider five general groups of predictive variables:
– Previous performance, including the severity and frequency of poor performance and
how recently the poor performance occurred.
– Current level and use of nonmortgage debt.
– Amount of time that credit ha
--

### Combine all chunks

In [42]:
all_docs: List[Document] = deling_docs + fraud_docs + regulatory_docs + score_docs
print(f"Total chunks: {len(all_docs)}")
print(f"By type: {pd.Series([d.metadata['doc_type'] for d in all_docs]).value_counts().to_dict()}")

Total chunks: 105
By type: {'regulatory': 53, 'fraud': 36, 'scorecard': 12, 'delinquency': 4}

## 🧩 Customer-Row → Narrative Document

### Build feature groups

In [43]:
# Fraud-oriented grouping of the SAME 47 columns already in df_enriched.
# Every column name here must exist in df_enriched.columns.

FRAUD_FEATURE_GROUPS = {
    "delinquency_history": [
        "max_recent_level_of_deliq",
        "max_deliq_12mts",
        "max_deliq_6mts",
        "recent_level_of_deliq",
        "max_delinquency_level",
        "num_times_delinquent",
        "time_since_first_deliquency",
        "time_since_recent_deliquency",
        "num_times_60p_dpd",
    ],
    "credit_utilisation": [
        "PL_utilization",
        "CC_utilization",
        "pct_currentBal_all_TL",
        "pct_opened_TLs_L6m_of_L12m",
        "max_unsec_exposure_inPct",
    ],
    "trade_line_activity": [
        "Total_TL_opened_L6M",
        "Tot_TL_closed_L6M",
        "Tot_TL_closed_L12M",
        "pct_tl_open_L6M",
        "pct_tl_closed_L6M",
        "pct_tl_open_L12M",
        "pct_tl_closed_L12M",
    ],
    "product_flags": [
        "PL_Flag", "CC_Flag", "HL_Flag", "GL_Flag",
        "first_prod_enq2", "last_prod_enq2",
    ],
    "account_history": [
        "num_std", "num_std_6mts", "num_std_12mts",
        "num_sub", "num_sub_6mts", "num_sub_12mts",
        "num_lss", "num_lss_6mts", "num_lss_12mts",
        "num_dbt", "num_dbt_6mts", "num_dbt_12mts",
    ],
    "enquiry_pattern": [
        "tot_enq",
    ],
    "payment_behaviour": [
        "Tot_Missed_Pmnt",
        "time_since_recent_payment",
    ],
    "identity_and_profile": [
        "AGE", "GENDER", "EDUCATION", "MARITALSTATUS",
        "NETMONTHLYINCOME",
        "Time_With_Curr_Empr",
        "Credit_Score",
    ],
}

### Derived features

In [44]:
def add_derived_features(row: pd.DataFrame) -> pd.Series:
    """Add derived features to a row based on existing features."""
    r = row.copy()
    def div(a, b):
        return float(a) / float(b) if pd.notna(a) and pd.notna(b) and b not in (0, None) else 0.0

    r["delinq_velocity"]   = div(row.get("num_deliq_6mts", 0), (row.get("num_deliq_12mts", 0) or 0) + 1)
    r["enq_velocity"]      = div(row.get("enq_L3m", 0), (row.get("enq_L12m", 0) or 0) + 1)
    r["unsecured_ratio"]   = div(row.get("Unsecured_TL", 0), (row.get("Total_TL", 0) or 0) + 1)
    r["active_ratio"]      = div(row.get("Tot_Active_TL", 0), (row.get("Total_TL", 0) or 0) + 1)
    r["recent_open_ratio"] = div(row.get("Total_TL_opened_L6M", 0), (row.get("Total_TL", 0) or 0) + 1)
    r["dpd_score"]         = float(row.get("num_times_30p_dpd", 0) or 0) * 1 + float(row.get("num_times_60p_dpd", 0) or 0) * 2
    r["asset_class_score"] = (
        float(row.get("num_sub", 0) or 0) * 1
        + float(row.get("num_dbt", 0) or 0) * 2
        + float(row.get("num_lss", 0) or 0) * 3
    )
    return r

df_enriched = df.apply(add_derived_features, axis=1)
print("\nAdded derived features to the dataset.")
df_enriched[["delinq_velocity","enq_velocity","unsecured_ratio","dpd_score","asset_class_score", "active_ratio", "recent_open_ratio"]].head(3)

Added derived features to the dataset.

,delinq_velocity,enq_velocity,unsecured_ratio,dpd_score,asset_class_score,active_ratio,recent_open_ratio
0,0.0,0.0,0.666667,0.0,0.0,0.166667,0.000000
1,0.0,0.0,0.500000,0.0,0.0,0.500000,0.000000
2,0.1,0.0,0.666667,0.0,0.0,0.888889,0.111111

## Convert each row to a narrative text chunk

In [45]:
def row_to_narrative(row: pd.Series, customer_id: Any = None) -> str:
    """Convert a customer row to a narrative string."""
    parts = [f"FRAUD_REVIEW customer_id={customer_id}"]

    for group, cols in FRAUD_FEATURE_GROUPS.items():
        lines = [f" {c}={row[c]}" for c in cols if c in row.index and pd.notna(row[c])]
        if lines:
            parts.append(f"[{group.upper()}]\n" + "\n".join(lines))

    return "\n".join(parts)

In [46]:
# Customer row -> Langchain Document
id_col = "customer_id" if "customer_id" in df_enriched.columns else None
label_col = "is_fraud" if "is_fraud" in df_enriched.columns else None

# Build function customer doc
def make_customer_doc(row: pd.Series) -> Document:
    cid = row[id_col] if id_col else row.name
    label = int(row[label_col]) if label_col and pd.notna(row[label_col]) else None
    return Document(
        page_content=row_to_narrative(row, cid),
        metadata={"doc_type": "customer_profile", "customer_id": str(cid), "label": label}
    )

# Check usage
print(make_customer_doc(df_enriched.iloc[0]).page_content[:600])
print(make_customer_doc(df_enriched.iloc[0]).metadata)

FRAUD_REVIEW customer_id=0
[DELINQUENCY_HISTORY]
 max_recent_level_of_deliq=29
 max_deliq_12mts=-99999
 max_deliq_6mts=-99999
 recent_level_of_deliq=29
 max_delinquency_level=29
 num_times_delinquent=11
 time_since_first_deliquency=35
 time_since_recent_deliquency=15
 num_times_60p_dpd=0
[CREDIT_UTILISATION]
 PL_utilization=0.798
 CC_utilization=-99999.0
 pct_currentBal_all_TL=0.798
 pct_opened_TLs_L6m_of_L12m=0.0
 max_unsec_exposure_inPct=13.333
[TRADE_LINE_ACTIVITY]
 Total_TL_opened_L6M=0
 Tot_TL_closed_L6M=0
 Tot_TL_closed_L12M=0
 pct_tl_open_L6M=0.0
 pct_tl_closed_L6M=0.0
 pct_tl_open_L12M
{'doc_type': 'customer_profile', 'customer_id': '0', 'label': None}

In [47]:
# Build customer documents
SAMPLE_N = 3000
df_sample = df_enriched.sample(n=SAMPLE_N, random_state=42)

customer_docs = [make_customer_doc(r) for _, r in tqdm(df_sample.iterrows(), total=len(df_sample), desc="Building customer docs")]
print(f"Customer docs sample: {len(customer_docs)}")
print("Customer doc sample:")
print(customer_docs[:1])

Building customer docs:   0%|          | 0/3000 [00:00<?, ?it/s]

Customer docs sample: 3000
Customer doc sample:
[Document(metadata={'doc_type': 'customer_profile', 'customer_id': '8564', 'label': None}, page_content='FRAUD_REVIEW customer_id=8564\n[DELINQUENCY_HISTORY]\n max_recent_level_of_deliq=26\n max_deliq_12mts=0\n max_deliq_6mts=0\n recent_level_of_deliq=26\n max_delinquency_level=26\n num_times_delinquent=2\n time_since_first_deliquency=14\n time_since_recent_deliquency=12\n num_times_60p_dpd=0\n[CREDIT_UTILISATION]\n PL_utilization=-99999.0\n CC_utilization=-99999.0\n pct_currentBal_all_TL=0.039\n pct_opened_TLs_L6m_of_L12m=0.0\n max_unsec_exposure_inPct=2.0\n[TRADE_LINE_ACTIVITY]\n Total_TL_opened_L6M=0\n Tot_TL_closed_L6M=0\n Tot_TL_closed_L12M=0\n pct_tl_open_L6M=0.0\n pct_tl_closed_L6M=0.0\n pct_tl_open_L12M=0.0\n pct_tl_closed_L12M=0.0\n[PRODUCT_FLAGS]\n PL_Flag=0\n CC_Flag=0\n HL_Flag=0\n GL_Flag=0\n first_prod_enq2=others\n last_prod_enq2=ConsumerLoan\n[ACCOUNT_HISTORY]\n num_std=0\n num_std_6mts=0\n num_std_12mts=0\n num_sub=0\n num_sub_6mts=0\n num_sub_12mts=0\n num_lss=0\n num_lss_6mts=0\n num_lss_12mts=0\n num_dbt=0\n num_dbt_6mts=0\n num_dbt_12mts=0\n[ENQUIRY_PATTERN]\n tot_enq=12\n[PAYMENT_BEHAVIOUR]\n Tot_Missed_Pmnt=0\n time_since_recent_payment=138\n[IDENTITY_AND_PROFILE]\n AGE=31\n GENDER=M\n EDUCATION=GRADUATE\n MARITALSTATUS=Single\n NETMONTHLYINCOME=30000\n Time_With_Curr_Empr=124\n Credit_Score=654')]

## Vector Store (ChromaDB + HuggingFace Embeddings)

In [48]:
EMBED_MODEL = "all-MiniLM-L6-v2" 

embeddings = HuggingFaceEmbeddings(
    model_name=EMBED_MODEL,
    encode_kwargs={"normalize_embeddings": True}
)
print(f"Embeddings model: {EMBED_MODEL}")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Embeddings model: all-MiniLM-L6-v2

## Persist collection to disk for ChromaDB

In [49]:
import chromadb
import shutil

# 1. Target the exact intended directory safely
PROJECT_ROOT = Path.cwd()
PERSIST_DIR = PROJECT_ROOT / "credit_risk" / "data_science" / "database" / "LLM" / "chroma_store"

# Print to double check the exact physical folder being touched
print(f"Chroma Store Path: {PERSIST_DIR.resolve()}")

# 2. Delete corrupt/legacy SQLite database directory if it exists
if PERSIST_DIR.exists():
    shutil.rmtree(PERSIST_DIR)

PERSIST_DIR.mkdir(parents=True, exist_ok=True)

# 3. Initialize PersistentClient explicitly
client = chromadb.PersistentClient(path=str(PERSIST_DIR))
print("✅ ChromaDB PersistentClient initialized cleanly!")

def build_load_collection(name: str, docs: List[Document]):
    """Store chromadb collection"""
    store = Chroma(
        client=client,
        collection_name=name,
        embedding_function=embeddings
    )
    existing = store._collection.count()

    if existing == 0 and docs:
        BATCH = 256 
        for i in range(0, len(docs), BATCH):
            store.add_documents(docs[i:i+BATCH])

    print(f"Collection '{name}': {store._collection.count()} vectors")
    return store

# Collection (customers + policies brief)
customer_store = build_load_collection("customer_profiles", customer_docs)
policy_docs = deling_docs + fraud_docs + regulatory_docs + score_docs
policy_store = build_load_collection("policy_documents", policy_docs)

print(f"Customer store: {customer_store._collection.count()} vectors")
print(f"Policy store: {policy_store._collection.count()} vectors")

Chroma Store Path: /Users/miftahhadiyannoor/Documents/credit_risk/data_science/notebooks/credit_risk/data_science/database/LLM/chroma_store
✅ ChromaDB PersistentClient initialized cleanly!
Collection 'customer_profiles': 3000 vectors
Collection 'policy_documents': 105 vectors
Customer store: 3000 vectors
Policy store: 105 vectors

## 🤖 LLM Client with HF → Groq Fallback

In [50]:
from huggingface_hub import login

login(token=HUGGINGFACE_API_KEY)

# Initialize HF and Groq clients
hf_client = InferenceClient(api_key=HUGGINGFACE_API_KEY) if HUGGINGFACE_API_KEY else None
groq_client = Groq(api_key=GROQ_API_KEY) if GROQ_API_KEY else None

print("✅ Logged in to Hugging Face Hub successfully.")

✅ Logged in to Hugging Face Hub successfully.

In [ ]:
from openai import OpenAI

# Define LLM AI by 9router clearly
NINEROUTER_MODEL = "sragent"
ninerouter_client = OpenAI(base_url=NINEROUTER_BASE_URL, api_key=NINEROUTER_API_KEY)

def extract_9router_text(resp) -> str:
    """
    Extract text from a 9router OpenAI-compatible response.

    Handles:
    - normal ChatCompletion responses
    - streaming ChatCompletion chunks
    - reasoning_content
    """

    # Normal non-streaming response
    if hasattr(resp, "choices"):
        chunks = []

        for choice in resp.choices:
            message = getattr(choice, "message", None)

            if message is not None:
                content = getattr(message, "content", None)

                if content:
                    chunks.append(content)

                reasoning = getattr(message, "reasoning_content", None)

                if reasoning and not content:
                    chunks.append(reasoning)

            # Reasoning directly on choice
            delta = getattr(choice, "delta", None)

            if delta is not None:


                content = getattr(delta, "content", None)
                if content:
                    chunks.append(content)

                reasoning = getattr(delta, "reasoning_content", None)
                if reasoning and not content:
                    chunks.append(reasoning)


        return "".join(chunks).strip()

    return ""

# 9Router Streaming
def call_9router(
    messages: List[Dict[str, str]],
    max_tokens: int = 1024,
    temperature: float = 0.3
) -> str:
    """
    Call 9router through its OpenAI-compatible API.

    Uses streaming because the successful curl request
    returns Server-Sent Events (data: {...}).
    """
    if not ninerouter_client:
        raise ValueError("9router client is not initialized. Check your API key and base URL.")

    print("🔄 Attempting fallback to "
          f"9router ('{NINEROUTER_MODEL}') for LLM response...")

    stream = ninerouter_client.chat.completions.create(
        model=NINEROUTER_MODEL,
        messages=messages,
        max_tokens=max_tokens,
        temperature=temperature,
        extra_body={"num_ctx": 16384},
        stream=True
    )

    output_parts = []
    reasoning_parts = []

    for chunk in stream:
        if not chunk.choices:
            continue

        choice = chunk.choices[0]
        delta = getattr(choice, "delta", None)

        if delta:
            # Normal generated text
            content = getattr(delta, "content", None)
            if content:
                output_parts.append(content)

            # Reasoning content
            reasoning = getattr(delta, "reasoning_content", None)
            if reasoning:
                reasoning_parts.append(reasoning)

    # If standard content exists, use it otherwise to fallback on reasoning content
    text_out = "".join(output_parts).strip()
    if not text_out:
        text_out = "".join(reasoning_parts).strip()

    if not text_out:
        raise ValueError("9router response contained no content or reasoning.")

    return text_out

In [52]:
def llm_chat(messages: List[Dict[str, str]], max_tokens: int = 512, temperature: float = 0.3) -> Dict[str, Any]:
    """Try HF first, fallback to Groq, then fallback to 9router combo 'sragent'."""

    # ========================================================
    # 1. HUGGING FACE
    # ========================================================
    if hf_client:
        try:
            resp = hf_client.chat.completions.create(
                model="Qwen/Qwen2.5-Coder-32B-Instruct",
                messages=messages,
                max_tokens=max_tokens,
                temperature=temperature
            )
            return {"text": resp.choices[0].message.content,
                    "provider": "huggingface"}
        except Exception as e:
            err_msg = str(e)
            if "402" in err_msg or "depleted" in err_msg:
                print("⚠️  HF quota depleted (402). Falling back to Groq...")
            else:
                print(f"❌  Hugging Face failed: {str(e)}")

    # ========================================================
    # 2. GROQ
    # ========================================================
    if groq_client:
        try:
            # Truncate message text to avoid Groq 8000 TPM limit (~20,000 chars approx 5,000 tokens)
            groq_messages = []

            for msg in messages:
                content = msg.get("content", "")

                if len(content) > 20000:
                    content = content[:20000] + "\n...[truncated due to TPM limits]"
                groq_messages.append({"role": msg["role"], "content": content})

            resp = groq_client.chat.completions.create(
                model="openai/gpt-oss-120b",
                messages=groq_messages,
                max_tokens=max_tokens,
                temperature=temperature
            )
            return {"text": resp.choices[0].message.content,
                    "provider": "groq"}
        except Exception as e:
            print(f"❌  Groq failed: {str(e)}")

    # ========================================================
    # 3. 9ROUTER
    # ========================================================
    if ninerouter_client:
        try:
            print(f"🔄 Attempting fallback to 9router ('{NINEROUTER_MODEL}')...")

            text_out = call_9router(
                messages=messages,
                max_tokens=max_tokens,
                temperature=temperature
            )
            print("✅  9router returned a response successfully.")

            return {"text": text_out, "provider": "9router (sragent)"}

        except Exception as e:
            print(f"❌  9router failed: {str(e)}")

    # If all fail, raise an error
    raise RuntimeError("‼️ All LLM providers failed. Check your API keys and network connectivity.")

# Sanity test
print(llm_chat([
    {"role": "user",
     "content": "Reply with the single word: READY"}
]))

⚠️  HF quota depleted (402). Falling back to Groq...
{'text': 'READY', 'provider': 'groq'}

### Load each model bundles

In [53]:
label_encoders = model_bundle['label_encoders']
scaler = model_bundle['scaler']
models = model_bundle['models']
print(f"Loaded label encoders: {list(label_encoders.keys())}")
print(f"Loaded scaler: {scaler}")
print(f"Loaded models: {list(models.keys())}")

Loaded label encoders: ['first_prod_enq2', 'EDUCATION', 'last_prod_enq2', 'MARITALSTATUS', 'GENDER']
Loaded scaler: StandardScaler()
Loaded models: ['Logistic Regression', 'Random Forest', 'Decision Tree', 'XGBoost', 'K-Nearest Neighbors']

## Scoring ML models return feature with SHAP values

In [54]:
import shap

def score_row(row: pd.Series, model_name: str) -> dict:
    """Score a single row using the specified model"""
    feature_cols = list(features.columns)

    X = pd.DataFrame([row.reindex(feature_cols).values], columns=feature_cols)

    for col, le in label_encoders.items():
        if col in X.columns:
            X[col] = X[col].astype(str).map(
                lambda s: le.transform([s])[0] if s in le.classes_ else -1
            )

    X = X.apply(pd.to_numeric, errors='coerce').fillna(0)
    X_scaled = pd.DataFrame(scaler.transform(X), columns=feature_cols)

    # Score using the specified model
    model = models[model_name]
    proba = model.predict_proba(X_scaled)[0]
    pred = int(model.predict(X_scaled)[0])
    classes = list(model.classes_)
    fraud_idx = classes.index(1) if 1 in classes else 0

     # Apply SHAP for feature importance
    top_features = []
    try:
        explainer = shap.Explainer(model)
        sv = explainer.shap_values(X_scaled)

        # For binary classification, pick class 1 (fraud class) SHAP values
        if len(sv.shape) == 3:
            row_shap = sv.values[0, :, fraud_idx]
        elif len(sv.shape) == 2:
            row_shap = sv.values[0, :]
        else:
            row_shap = np.array(sv[0])

        # Get original raw feature values for display
        raw_values = row.reindex(feature_cols).to_dict()

        # Build feature list sorted by absolute SHAP contribution
        feature_impacts = [
            {
                "name": feature_name,
                "value": raw_values.get(feature_name, None),
                "contribution": float(shap_val),
                "abs_impact": abs(float(shap_val))
            }
            for feature_name, shap_val in zip(feature_cols, row_shap)
        ]

        # Sort by impact and keep top 5
        sorted_features = sorted(feature_impacts, key=lambda x: x["abs_impact"], reverse=True)

        top_features = [
            {
                "name": f["name"],
                "value": f["value"],
                "contribution": f["contribution"]
            }
            for f in sorted_features[:5]
        ]

    except Exception as e:
        # Fallback to feature_importances_ or coef_ is SHAP fails
        if hasattr(model, "feature_importances_"):
            importances = model.feature_importances_
            top_idx = np.argsort(importances)[::-1][:5]
            top_features = [
                {
                    "name": feature_cols[i],
                    "value": row[feature_cols[i]],
                    "contribution": float(importances[i])
                }
                for i in top_idx
            ]

    return {
        "fraud_probability": float(proba[fraud_idx]),
        "predicted_label": pred,
        "model_used": model_name,
        "top_features": top_features
    }

## 🧠 RAG Pipeline

In [55]:
def retrieve_context(row: pd.Series, k_customers: int = 3, k_policies: int = 5) -> Dict[str, Any]:
    """Retrieve relevant policy and similar customer documents for a given row"""
    query = row_to_narrative(row)
    cust_hits = customer_store.similarity_search(query, k=k_customers)

    # Policy hits: bias query toward delinquency + enquiries since driver risk
    policy_query = (
        f"{query}\n"
        f"focus: delinquency, {row.get('num_deliq_12mts', 0)} misses in 12 months"
        f"unsecured ratio {row.get('unsecured_ratio', 0):.2f}"
        f"enquiries in last 12 months: {row.get('enq_L12m', 0)}"
        f"asset class score: {row.get('asset_class_score', 0):.2f}"
        f"credit card enquiries: {row.get('CC_enq_L12m', 0)}"
    )
    policy_hits = policy_store.similarity_search(policy_query, k=k_policies)

    return {"customers": cust_hits, "policies": policy_hits}

## Build prompt (system + context + task)

In [56]:
FRAUD_SYSTEM_PROMPT = """You are a senior fraud risk analyst assistant for a bank/fintech.

The ML fraud model has ALREADY produced a fraud probability and a binary label
(1 = fraud, 0 = no fraud). You DO NOT compute, adjust, or override that score.

Your job is to:
    1. Interpret the fraud probability in plain language for a fraud ops analyst.
    2. Identify the single most likely fraud typology the case resembles, using ONLY the typology definitions
    present in the RETRIEVED POLICIES.
    3. List the concrete red flags observed in the CUSTOMER FEATURES. For each red flag, name the feature and quote its value.
    4. Map the case to the retrieved policies and cite them by their exact reference string
    (e.g. "Fraud_Typologies_and_Red Flags.pdf p12").
    5. Recommend exactly ONE action from the ALLOWED ACTIONS list.
    6. State your confidence (0.0-1.0) and, if below 0.6, set needs_human_review=True.

Had rules:
    - NEVER ivent numbers. Use only values that appear in the ML FRAUD OUTPUT
      or CUSTOMER FEATURES blocks.
    - NEVER invent a typology. Pick "unknown" if none of the retrieved typology
      definitions match.
    - NEVER invent a policy citation. Every entry in policy_refs MUST appear
      verbatim in the RETRIEVED POLICIES block.
    - If a required input is missing, write "not available" and explain briefly
      in key_drivers.
    - Prefer specificity: name features and values, not generic phrases.

You must return STRICT JSON only. No prose outside JSON. No markdown fences.
"""

# Constants the prompt ferences
ALLOWED_TYPOLOGIES = [
    "application_fraud",
    "account_takeover",
    "synthetic_identity",
    "first_party_fraud",
    "friendly_fraud",
    "money_mule",
    "card_not_present",
    "unknown",
]

ALLOWED_ACTIONS = [
    "allow",
    "step_up_auth",
    "manual_review",
    "block", 
    "report_sar",
]

REQUIRED_KEYS = {
    "fraud_band",
    "typology",
    "red_flags",
    "key_drivers",
    "recommended_action",
    "policy_refs",
    "confidence",
    "needs_human_review",
}

FRAUD_THRESHOLDS = {
    "auto_allow_below": 0.10,
    "auto_block_above": 0.85,
    "k_customers": 5,
    "k_policies": 5,
}

In [57]:
# Apply the system prompt on building the messages for the LLM
def build_fraud_messages(row: pd.Series, ml_results: dict, context: dict) -> List[dict]:
    """Divide by policies block, similar cases block, ML output block, and customer features block."""
    # --- policies block ---
    policies_txt = "\n\n".join(
        f"[Policy ref {i+1} | doc={d.metadata.get('doc', 'unknown')} "
        f"p{d.metadata.get('page', '?')}]\n{d.page_content}"
        for i, d in enumerate(context.get("policies", []))
    ) or "none retrieved"

    # --- similar cases block ---
    similar_txt = "\n\n".join(
        f"[Similar case {i+1} | label={d.metadata.get('label', '?')}]\n"
        f"{d.page_content[:600]}"
        for i, d in enumerate(context.get("customers", []))
    ) or "none retrieved"

    # --- ML output block ---
    top_feat_txt = "\n".join(
        f"- {f['name']} = {f['value']} (contribution {f.get('contribution', 0):+.4f})"
        for f in ml_results.get("top_features", [])
    ) or "not available"

    ml_block = (
        "fraud_probability (0-1): {ml_results['fraud_probability']:.4f}\n"
        f"predicted_label (1=fraud, 0=no fraud): {ml_results['predicted_label']}\n"
        f"model_name: {ml_results.get('model_name', 'not available')}\n"
        f"top_contributing_features:\n{top_feat_txt}"
    )

    # --- customer features block ---
    customer_txt = row_to_narrative(row, customer_id=row.get("PROSPECTID", row.name))

    # -- User prompt --
    user_prompt = f"""CUSTOMER FEATURES:
    {customer_txt}

    ML FRAUD OUTPUT:
    {ml_block}

    SIMILAR HISTORICAL CASES:
    {similar_txt}

    RETRIEVED POLICIES:
    {policies_txt}

    ALLOWED TYPOLOGIES (choose exactly one, or "unknown"):
    {", ".join(ALLOWED_TYPOLOGIES)}

    ALLOWED ACTIONS (choose exactly one):
    {", ".join(ALLOWED_ACTIONS)}
    
    TASK:
    Return ONLY a JSON object with EXACTLY these keys:
    {{
        "fraud_band": "Low" | "Medium" | "High" | "Critical",
        "typology": "<one of the allowed typologies>",
        "red_flags": [{{"feature": "...", "value": "...", "why": "..."}}],
        "key_drivers": ["...", "..."],
        "recommended_action": "<one of the allowed actions>",
        "policy_refs": ["...", "..."],
        "confidence": 0.0,
        "needs_human_review": true
    }}
    """

    return [
        {"role": "system", "content": FRAUD_SYSTEM_PROMPT},
        {"role": "user", "content": user_prompt}
    ]

## JSON Parsing

In [ ]:
def parse_fraud_output(text: str) -> dict:
    txt = re.sub(r"^```(json)?|```$", "", text.strip(), flags=re.MULTILINE).strip()

    try:
        out = json.loads(txt)
    except json.JSONDecodeError:
        m = re.search(r"\{.*\}", txt, flags=re.DOTALL)
        blob = m.group(0) if m else "{}"
        try:
            out = json.loads(blob)
        except json.JSONDecodeError:
            # one repair pass via the LLM
            repair = llm_chat(
                messages=[
                    {"role": "system",
                     "content": "Fix malformed JSON. Return ONLY valid JSON."},
                    {"role": "user", "content": blob},
                ],
                max_tokens=512,
                temperature=0.0,
            )
            try:
                out = json.loads(repair["text"])
            except json.JSONDecodeError:
                out = {"raw_text": txt, "parse_error": "unrecoverable"}

    if out.get("typology") not in ALLOWED_TYPOLOGIES:
        out["typology"] = "unknown"
    if out.get("recommended_action") not in ALLOWED_ACTIONS:
        out["recommended_action"] = "manual_review"
    if out.get("recommended_action") in {"block", "report_sar"}:
        out["needs_human_review"] = True

    # Always fill missing required keys with defaults so no missing_keys ever appears
    defaults = {
        "fraud_band": "Medium",
        "typology": "unknown",
        "red_flags": [],
        "key_drivers": [],
        "recommended_action": "manual_review",
        "policy_refs": [],
        "confidence": 0.5,
        "needs_human_review": True,
    }
    for k, v in defaults.items():
        if k not in out:
            out[k] = v

    return out

## 📊 Score a single row and generate the fraud analysis output

In [ ]:
# Usage: Score a single row and generate the fraud analysis output
row = df_enriched.iloc[0]
ml_results = score_row(row, model_name="Random Forest")
context = retrieve_context(row, k_customers=3, k_policies=5)
messages = build_fraud_messages(row, ml_results, context)
out = llm_chat(messages, max_tokens=512, temperature=0.3)
parsed = parse_fraud_output(out["text"])
print(json.dumps(parsed, indent=2))

⚠️  HF quota depleted (402). Falling back to Groq...
❌  Groq failed: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01katr34q2erz904dzn297vh2r` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 198685, Requested 5681. Please try again in 31m26.111999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
🔄 Attempting fallback to 9router ('sragent')...
🔄 Attempting fallback to 9router ('sragent') for LLM response...
✅  9router returned a response successfully.
{
  "fraud_band": "High",
  "typology": "application_fraud",
  "red_flags": [
    {
      "feature": "Credit_Score",
      "value": "696",
      "why": "Score is in the lower end of the 600\u2011699 band, indicating higher credit risk."
    },
    {
      "feature": "PL_utilization",
      "value": "0.798",
      "why": "Personal loan utilization is nearly 80%, suggesting the customer is heavily using available credit."
    },
    {
      "feature": "max_recent_level_of_deliq",
      "value": "29",
      "why": "Recent delinquency level of 29 days shows the account is already past due."
    },
    {
      "feature": "num_std",
      "value": "21",
      "why": "A high number of standard inquiries signals frequent credit checks, often associated with risky behavior."
    },
    {
      "feature": "tot_enq",
      "value": "6",
      "why": "Multiple recent credit inquiries can indicate aggressive credit seeking."
    },
    {
      "feature": "time_since_recent_deliquency",
      "value": "15",
      "why": "Only 15 days since the most recent delinquency, indicating recent payment difficulty."
    }
  ],
  "key_drivers": [
    "ML fraud probability not provided in the output (placeholder present)."
  ],
  "recommended_action": "manual_review",
  "policy_refs": [
    "Policy ref 4 | doc=unknown p?"
  ],
  "confidence": 0.3,
  "needs_human_review": true
}

## Threshold fraud to ristrict out of skewed

In [ ]:
def decide_fraud(row, model_name: str):
    """Fraud decision pipeline with complete required output fields.
    For AUTO_ALLOW and AUTO_BLOCK decisions, we construct a full result
    containing all REQUIRED_KEYS, avoiding missing_keys.
    """
    ml = score_row(row, model_name=model_name)
    fp = ml["fraud_probability"]

    # Helper to build result for auto paths
    def build_auto_result(decision: str):
        # Determine fraud_band based on thresholds
        if fp < FRAUD_THRESHOLDS["auto_allow_below"]:
            band = "Low"
        elif fp > FRAUD_THRESHOLDS["auto_block_above"]:
            band = "Critical"
        else:
            band = "Medium"
        defaults = {
            "fraud_band": band,
            "typology": "unknown",
            "red_flags": [],
            "key_drivers": [],
            "recommended_action": "allow" if decision == "AUTO_ALLOW" else "block",
            "policy_refs": [],
            "confidence": fp,
            "needs_human_review": fp < 0.6,
        }
        return {"decision_route": decision, "provider": "ML_Policy_Engine", **ml, **defaults}

    if fp < FRAUD_THRESHOLDS["auto_allow_below"]:
        return build_auto_result("AUTO_ALLOW")
    if fp > FRAUD_THRESHOLDS["auto_block_above"]:
        return build_auto_result("AUTO_BLOCK")

    # RAG path for intermediate probabilities
    context = retrieve_context(row)
    messages = build_fraud_messages(row, ml, context)
    out = llm_chat(messages, max_tokens=512, temperature=0.3)
    parsed = parse_fraud_output(out["text"])
    # Ensure all required keys are present (fallback to None)
    for k in REQUIRED_KEYS:
        if k not in parsed:
            parsed[k] = None
    return {"decision_route": "RAG_LLM", "provider": out["provider"], **ml, **parsed}

## 🧪 Call the Sumarize the LLM

In [ ]:
# JSON parse function
def json_converter(obj):
    """Convert NumPy types to standard Python types for JSON serialization."""
    if isinstance(obj, (np.integer, np.int64, np.int32)):
        return int(obj)
    elif isinstance(obj, (np.floating, np.float64, np.float32)):
        return float(obj)
    elif isinstance(obj, (np.ndarray,)):
        return obj.tolist()
    elif isinstance(obj, (np.bool_)):
        return bool(obj)
    return str(obj)

# Component structured output
row = df_enriched.iloc[1]
ml_results = score_row(row, model_name="XGBoost")
context = retrieve_context(row, k_customers=3, k_policies=5)
messages = build_fraud_messages(row, ml_results, context)
out = llm_chat(messages=messages, max_tokens=512, temperature=0.3)
parsed = parse_fraud_output(out["text"])

final = {
    "prospectid": int(row["PROSPECTID"]),
    "provider": out["provider"],
    "context": context,
    **ml_results,
    **parsed
}

print("Final structured output:")
print(json.dumps(final, indent=2, default=json_converter))

⚠️  HF quota depleted (402). Falling back to Groq...
❌  Groq failed: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01katr34q2erz904dzn297vh2r` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 198655, Requested 5540. Please try again in 30m12.24s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
🔄 Attempting fallback to 9router ('sragent')...
🔄 Attempting fallback to 9router ('sragent') for LLM response...
✅  9router returned a response successfully.
⚠️  HF quota depleted (402). Falling back to Groq...
Final structured output:
{
  "prospectid": 2,
  "provider": "9router (sragent)",
  "context": {
    "customers": [
      "page_content='FRAUD_REVIEW customer_id=1114\n[DELINQUENCY_HISTORY]\n max_recent_level_of_deliq=0\n max_deliq_12mts=0\n max_deliq_6mts=0\n recent_level_of_deliq=0\n max_delinquency_level=-99999\n num_times_delinquent=0\n time_since_first_deliquency=-99999\n time_since_recent_deliquency=-99999\n num_times_60p_dpd=0\n[CREDIT_UTILISATION]\n PL_utilization=-99999.0\n CC_utilization=-99999.0\n pct_currentBal_all_TL=0.25\n pct_opened_TLs_L6m_of_L12m=0.0\n max_unsec_exposure_inPct=0.75\n[TRADE_LINE_ACTIVITY]\n Total_TL_opened_L6M=0\n Tot_TL_closed_L6M=0\n Tot_TL_closed_L12M=0\n pct_tl_open_L6M=0.0\n pct_tl_closed_L6M=0.0\n pct_tl_open_L12M=1.0\n pct_tl_closed_L12M=0.0\n[PRODUCT_FLAGS]\n PL_Flag=0\n CC_Flag=0\n HL_Flag=0\n GL_Flag=0\n first_prod_enq2=PL\n last_prod_enq2=PL\n[ACCOUNT_HISTORY]\n num_std=0\n num_std_6mts=0\n num_std_12mts=0\n num_sub=0\n num_sub_6mts=0\n num_sub_12mts=0\n num_lss=0\n num_lss_6mts=0\n num_lss_12mts=0\n num_dbt=0\n num_dbt_6mts=0\n num_dbt_12mts=0\n[ENQUIRY_PATTERN]\n tot_enq=1\n[PAYMENT_BEHAVIOUR]\n Tot_Missed_Pmnt=0\n time_since_recent_payment=83\n[IDENTITY_AND_PROFILE]\n AGE=39\n GENDER=M\n EDUCATION=12TH\n MARITALSTATUS=Married\n NETMONTHLYINCOME=32000\n Time_With_Curr_Empr=53\n Credit_Score=683' metadata={'customer_id': '1114', 'doc_type': 'customer_profile'}",
      "page_content='FRAUD_REVIEW customer_id=11582\n[DELINQUENCY_HISTORY]\n max_recent_level_of_deliq=0\n max_deliq_12mts=0\n max_deliq_6mts=0\n recent_level_of_deliq=0\n max_delinquency_level=-99999\n num_times_delinquent=0\n time_since_first_deliquency=-99999\n time_since_recent_deliquency=-99999\n num_times_60p_dpd=0\n[CREDIT_UTILISATION]\n PL_utilization=-99999.0\n CC_utilization=-99999.0\n pct_currentBal_all_TL=0.103\n pct_opened_TLs_L6m_of_L12m=0.0\n max_unsec_exposure_inPct=0.56\n[TRADE_LINE_ACTIVITY]\n Total_TL_opened_L6M=0\n Tot_TL_closed_L6M=0\n Tot_TL_closed_L12M=0\n pct_tl_open_L6M=0.0\n pct_tl_closed_L6M=0.0\n pct_tl_open_L12M=0.333\n pct_tl_closed_L12M=0.0\n[PRODUCT_FLAGS]\n PL_Flag=0\n CC_Flag=0\n HL_Flag=0\n GL_Flag=0\n first_prod_enq2=others\n last_prod_enq2=ConsumerLoan\n[ACCOUNT_HISTORY]\n num_std=0\n num_std_6mts=0\n num_std_12mts=0\n num_sub=0\n num_sub_6mts=0\n num_sub_12mts=0\n num_lss=0\n num_lss_6mts=0\n num_lss_12mts=0\n num_dbt=0\n num_dbt_6mts=0\n num_dbt_12mts=0\n[ENQUIRY_PATTERN]\n tot_enq=6\n[PAYMENT_BEHAVIOUR]\n Tot_Missed_Pmnt=0\n time_since_recent_payment=41\n[IDENTITY_AND_PROFILE]\n AGE=38\n GENDER=M\n EDUCATION=UNDER GRADUATE\n MARITALSTATUS=Single\n NETMONTHLYINCOME=24120\n Time_With_Curr_Empr=114\n Credit_Score=711' metadata={'customer_id': '11582', 'doc_type': 'customer_profile'}",
      "page_content='FRAUD_REVIEW customer_id=1900\n[DELINQUENCY_HISTORY]\n max_recent_level_of_deliq=0\n max_deliq_12mts=0\n max_deliq_6mts=0\n recent_level_of_deliq=0\n max_delinquency_level=-99999\n num_times_delinquent=0\n time_since_first_deliquency=-99999\n time_since_recent_deliquency=-99999\n num_times_60p_dpd=0\n[CREDIT_UTILISATION]\n PL_utilization=-99999.0\n CC_utilization=-99999.0\n pct_currentBal_all_TL=0.5\n pct_opened_TLs_L6m_of_L12m=1.0\n max_unsec_exposure_inPct=0.327\n[TRADE_LINE_ACTIVITY]\n Total_TL_opened_L6M=1\n Tot_TL_closed_L6M=0\n Tot_TL_closed_L12M=0\n pct_tl_open_L6M=0.5\n pct_tl_closed_L6M=0.0\n pct_tl_open_L12M=0.5\n pct_tl_closed_L12M=0.0\n[PRODUCT_FLAGS]\n PL_Flag=0\n CC_Flag=0\n HL_Flag=0\n GL_Flag=0\n first_prod_enq2=others\n last_prod_enq2=PL\n[ACCOUNT_HISTORY]\n num_std=1\n num_std_6mts=0\n num_std_12mts=0\n num_sub=0\n num_sub_6mts=0\n num_sub_12mts=0\n num_lss=0\n num_lss_6mts=0\n num_lss_12mts=0\n num_dbt=0\n num_dbt_6mts=0\n num_dbt_12mts=0\n[ENQUIRY_PATTERN]\n tot_enq=2\n[PAYMENT_BEHAVIOUR]\n Tot_Missed_Pmnt=0\n time_since_recent_payment=110\n[IDENTITY_AND_PROFILE]\n AGE=26\n GENDER=M\n EDUCATION=12TH\n MARITALSTATUS=Married\n NETMONTHLYINCOME=52000\n Time_With_Curr_Empr=66\n Credit_Score=682' metadata={'doc_type': 'customer_profile', 'customer_id': '1900'}"
    ],
    "policies": [
      "page_content='114 and 315 of the FACT Act \n(15 USC 1681m(e) and 15 USC 1681c(h), respectively), 12 CFR 41, and any other \napplicable laws and regulations. Further, MIS should provide management with the ability to \nidentify and report suspicious activities. If a program is not working effectively, management \nshould take steps to discontinue or modify it. Examiners should evaluate the bank\u2019s MIS for \npertinent information and accuracy and may need to criticize any absence of appropriate \ntracking and monitoring. \n \nIntroduction > Risk Management \nComptroller\u2019s Handbook 41 Credit Card Lending \nOne report, called the \u201crollover,\u201d or \u201croll-rate\u201d report, is particularly important. Through this \nreport, bank management can review the number and dollar volume of accounts that move \nfrom current to 30 days delinquent, 30 to 60 days delinquent, etc. This information aids \nmanagement in projecting accurately the charge-off rates as far as six months into the future \nand informs decisions regarding collection staffing levels. \n \nDelinquency and charge-off reports serve as valuable tools in evaluating collection \neffectiveness. Bank management should review these reports for the entire portfolio as well \nas on a program-by-program basis. Many credit card operations report delinquencies using \ntwo formats: end-of-month (EOM) and sum-of-cycle (SOC). EOM delinquencies are used for \ncall report purposes and reflect outstanding delinquencies at month-end as a percentage of \noutstanding receivables. SOC reports compute delinquencies for each billing cycle, then \naggregate these cycles to determine delinquency for the total portfolio. Unlike EOM reports, \nSOC reports ignore the \u201ccleaning up\u201d of delinquencies between the end of the cycle date and \nthe end of the month. \n \nBank management may find reports that analyze delinquencies and charge-offs on a \u201clagged\u201d \nbasis useful, especially if a portfolio has experienced significant growth. Such analyses \ncalculate current delinquency and charge-off figures as a percentage of receivables \noutstanding six or 12 months prior. A \u201cblock\u201d or \u201cstatus code\u201d report provides valuable \ninformation for reviewing the composition of the portfolio (e.g., the number and dollar \namounts of fixed-payment, bankruptcy, fraud, deceased, and canceled accounts). Other \nreports should include actual versus budgeted performance, impact of changes in collection \nstrategies, and performance of behavioral or other scoring models. \n \nDelinquency, Classification, and Charge-Off Policies \n \nBank management should regularly review the quality of the portfolio through a variety of \nmeans, including past due, charge-off, and profitability reports. Management should be able \nto quickly identify trends in the portfolio and react appropriately.  \n \nGuidance on account classification and charge-off practices is provided by OCC Bulletin \n2000-20, \u201cUniform Retail Credit Classification and Account Management Policy: Policy \nImplementation,\u201d which, in general, advises that credit card accounts be charged off when \nthey become 180 days delinquent. Accounts that are placed in long-term amortizing workout \nprograms should be charged off at 120 days. The bulletin also addresses accounts that are \naffected by bankruptcy, fraud, and death, and examiners should review this issuance closely \nwhen assessing a bank\u2019s collection activities.  \n \nAll accounts that are 90 to 180 days delinquent should be classified as substandard. \nExaminers are not precluded from classifying additional portfolio segments as substandard, \nhowever, if a review of credit information and loss performance indicates that such \nclassification is warranted. For example, a subprime program in which the roll-to-loss rate \nfrom 30 days delinquent is between 30 percent and 50 percent may indicate a need to classify \nthese assets substandard rather than waiting until they are 90 days delinquent, when the roll-\nto-loss rate is 90 percent. Likewise, it may be appropriate to charge off these accounts sooner \nIntroduction > Risk Management \nComptroller\u2019s Handbook 42 Credit Card Lending \nthan 180 days if roll-rate information suggests that almost 100 percent of the accounts roll to \nloss earlier in the cycle. \n \nRecoveries \n \nRecoveries represent collection activities conducted after an account is charged off. The rate \nof recovery depends on many factors, including \n \n\u2022 previous collection efforts. \n\u2022 depth and experience of staff. \n\u2022 adequacy of systems and controls. \n\u2022 use of technology. \n \nRecovery activities are generally conducted internally and then out-placed to collection \nagencies after several months. When out-placing accounts, the bank should maintain strict \ncontrols and appropriate systems to evaluate each agency\u2019s performance. Collection agencies \nreceive a percentage of the dollars collected, typically between 30 percent and 60 percent. \nThe amount varies based on whether the agency is the primary collector (the first to work the \naccounts) or the secondary or tertiary collector. Fees are lowest for the primary agency and \nhighest for the tertiary agency. A bank should periodically rotate out-placed accounts among \nagencies to ensure that the accounts are actively and appropriately worked. \n \nWhen banks select agencies to which they out-place accounts, the banks should perform due \ndiligence to ensure that an agency is, among other things, properly licensed, bonded, and \ninsured. Banks also should have systems to monitor the agencies on an ongoing basis to \nensure that the agencies operate prudently. Bank management should follow the guidance in \nOCC Bulletin 2013-29, \u201cThird-Party Relationships: Risk Management Guidance,\u201d when \nworking with outside parties to collect accounts. \n \nConsumer Debt Sales  \n \nAs providers of consumer credit, banks lend money to be repaid with interest. Banks \nunderwrite the loans and price them according to the risk associated with the type of lending \nand the customers\u2019 creditworthiness. A percentage of the loans that banks make goes unpaid. \nUnder guidelines set out in OCC Bulletin 2000-20, \u201cUniform Retail Credit Classification and \nAccount Management Policy: Policy Implementation,\u201d banks should charge off open-end \ncredit at 180 days past due. Even though the bank has charged off the loan, the borrower \ngenerally continues to have an obligation to repay the debt. At that point, the bank faces a \nbusiness decision on how to recover the loss or whether to pursue collection at all.  \n \nThe majority of debt that banks charge off and sell to debt buyers is credit card debt, but \nbanks also sell to debt buyers other delinquent debts, such as auto, home equity, mortgage, \nand student loans. Most debt-sale arrangements involve banks selling debt outright to debt \nbuyers. Banks may price debt based on a small percentage of the outstanding contractual \naccount balances. Typically, debt buyers obtain the right to collect the full amount of the \ndebts. Debt buyers may collect the debts or employ a network of agents to do so. Notably, \nIntroduction > Risk Management \nComptroller\u2019s Handbook 43 Credit Card Lending \nsome banks and debt buyers agree to contractual \u201cforward-flow\u201d arrangements, in which the \nbanks continue to sell accounts to the debt buyers on an ongoing basis. This section focuses \nspecifically on debt sales. Many of the principles, however, also apply when a bank hires a \nthird party to collect debt on its behalf. \n \nWhen a bank sells consumer debt, the bank should have policies, procedures, and practices \nthat help ensure that any third party purchasing the bank\u2019s consumer debt for its own \ncollection treats customers fairly and consistently, in accordance with the bank\u2019s expectations \nand applicable law. Increased risk most often arises from poor planning and inferior \nperformance or service on the part of the debt buyer, and this may result in legal costs or loss \nof business for the bank. Selling debt to a debt buyer can significantly increase a bank\u2019s risk \nprofile, particularly in the areas of operational, reputation, compliance, and strategic risks. \n \n\u2022 Operational risk: Inadequate systems and controls can place the bank at risk for selling \ndebt with inaccurate information regarding the characteristics of accounts. \n\u2022 Reputation risk: When banks sell consumer debt to debt buyers that engage in practices \nperceived to be unfair or detrimental to customers, banks can lose community support \nand business. \n\u2022 Compliance risk: This risk exists when banks do not appropriately assess current and \nongoing debt buyer collection practices for compliance with laws, fair treatment of \ncustomers, or the bank\u2019s policies and procedures.  \n\u2022 Strategic risk. Decisions to sell debt to debt buyers should be carefully analyzed by \nexaminers to assess consistency with the bank\u2019s strategic goals and whether capable \nmanagement and staff are in place to perform due diligence and carry out debt sales.  \n \nExaminers are encouraged to refer to OCC Bulletin 2014-37, \u201cConsumer Debt Sales: Risk \nManagement Guidance,\u201d for guidance as they review bank debt sales activities. Likewise, \nexaminers should refer to OCC Bulletin 2013-29, \u201cThird-Party Relationships: Risk \nManagement Guidance,\u201d which sets forth guidance for effectively managing risks associated \nwith vendors and third-party service providers, including third-party service providers \ncollecting debt on behalf of the bank (debt placement relationships). Additionally, examiners \nshould complete a careful review of these sales to assess that they are consistent with \ngenerally accepted accounting principles (GAAP). \n \nFederal statutes applicable to debt sales include the following:  \n \n\u2022 FDCPA: This applies to debts incurred primarily for the consumer\u2019s personal, family, or \nhousehold purposes. Under the FDCPA, \u201cdebt collector\u201d is defined broadly to encompass \ndebt buyers working on behalf of original creditors, including banks. \n\u2022 FCRA: The FCRA, which is implemented by Regulation V, regulates the collection, \ndissemination, and use of consumer information, including consumer credit information. \n\u2022 Gramm\u2013Leach\u2013Bliley Act (GLBA): Certain provisions of the GLBA and Regulation P, \nwhich implements the GLBA, require banks to provide consumers with privacy notices at \nthe time consumer relationships are established and annually thereafter. In addition, this \nlaw imposes limitations on banks\u2019 sharing of nonpublic personal information with debt \nbuyers. \nIntroduction > Risk Management \nComptroller\u2019s Handbook 44 Credit Card Lending \n\u2022 ECOA: The ECOA and its implementing regulation, Regulation B, prohibit \ndiscrimination in any aspect of a credit transaction on a \u201cprohibited basis.\u201d The \nprohibition against discrimination in any aspect of a credit transaction on a prohibited \nbasis includes collection procedures.  \n\u2022 FTC Act: Section 5 of the FTC Act prohibits UDAP in or affecting commerce. Public \npolicy may also be considered in determining if acts or practices are unfair.  \n\u2022 Dodd\u2013Frank Act: Section 1036(a)(1) of the Dodd\u2013Frank Act, 12 USC 5536(a), \nprohibits a covered entity from engaging in UDAAP. \n \nFraud Control \n \nFraud is a continuing problem with credit card programs. By its very nature, the product is an \neasily obtainable, unsecured line of credit managed by the consumer, making it an ideal \nmechanism for fraud. The bank card associations, issuers, and acquirers, the U.S. Postal \nService, and other entities have strengthened systems and controls to reduce fraudulent \nactivities. Despite significant advances in detection, however, fraud\u2014specifically identity \ntheft\u2014continues to be a major issue in the credit card industry.  \n \nBank management should have appropriate systems and controls in place to control fraud \nlosses. Systems and controls should include procedures for reporting suspicious activity. The \nproper training of bank employees regarding fraud systems and controls, fraud recognition \nand handling, and accurate MIS reporting are important for maintaining fraud losses at or \nbelow industry averages. Training programs for this area should include the \u201cIdentity Theft \nRed Flags and Address Discrepancies\u201d rules implementing sections' metadata={'chunk_id': 2, 'doc_type': 'scorecard', 'max_score': 315, 'min_score': 114}",

## Batch evaluation of the fraud pipeline

In [62]:
import time
from tqdm import tqdm

N_TEST = 200
test_rows = df_enriched.sample(n=N_TEST, random_state=42)

results = []
for i, (_, row) in enumerate(tqdm(test_rows.iterrows(), total=N_TEST)):
    try:
        r = decide_fraud(row, model_name="Random Forest")
    except Exception as e:
        r = {"error": str(e)}

    r["row_index"] = int(row.name)

    # Ensure provider
    if "provider" not in r:
        r["provider"] = None

    results.append(r)
    time.sleep(0.3)  # rate limit LLM

# Into DataFrame for analysis
results_df = pd.DataFrame(results)

cols_to_show = [
    "row_index",
    "decision_route",        # AUTO_ALLOW | AUTO_BLOCK | RAG_LLM
    "provider",              # huggingface | groq | ML_Policy_Engine | None
    "fraud_probability",     # 0-1
    "fraud_band",            # Low | Medium | High | Critical (only for RAG_LLM)
    "typology",              # account_takeover, ... (only for RAG_LLM)
    "recommended_action",    # allow | step_up_auth | manual_review | block | report_sar
    "confidence",            # 0-1 (LLM's self-reported confidence)
    "needs_human_review",    # bool
]
available_cols = [c for c in cols_to_show if c in results_df.columns]
results_df[available_cols].head(20)

 32%|███▏      | 63/200 [00:24<00:52,  2.62it/s]

⚠️  HF quota depleted (402). Falling back to Groq...
❌  Groq failed: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01katr34q2erz904dzn297vh2r` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 198924, Requested 5740. Please try again in 33m34.848s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
🔄 Attempting fallback to 9router ('sragent')...
🔄 Attempting fallback to 9router ('sragent') for LLM response...
✅  9router returned a response successfully.
⚠️  HF quota depleted (402). Falling back to Groq...

 32%|███▏      | 64/200 [00:34<07:42,  3.40s/it]

⚠️  HF quota depleted (402). Falling back to Groq...
❌  Groq failed: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01katr34q2erz904dzn297vh2r` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199253, Requested 5185. Please try again in 31m57.216s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
🔄 Attempting fallback to 9router ('sragent')...
🔄 Attempting fallback to 9router ('sragent') for LLM response...
✅  9router returned a response successfully.
⚠️  HF quota depleted (402). Falling back to Groq...

 51%|█████     | 102/200 [00:59<00:37,  2.59it/s]

⚠️  HF quota depleted (402). Falling back to Groq...
❌  Groq failed: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01katr34q2erz904dzn297vh2r` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199548, Requested 5743. Please try again in 38m5.712s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
🔄 Attempting fallback to 9router ('sragent')...
🔄 Attempting fallback to 9router ('sragent') for LLM response...
✅  9router returned a response successfully.
⚠️  HF quota depleted (402). Falling back to Groq...

 54%|█████▎    | 107/200 [01:11<01:48,  1.16s/it]

⚠️  HF quota depleted (402). Falling back to Groq...
❌  Groq failed: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01katr34q2erz904dzn297vh2r` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199871, Requested 5448. Please try again in 38m17.808s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
🔄 Attempting fallback to 9router ('sragent')...
🔄 Attempting fallback to 9router ('sragent') for LLM response...
✅  9router returned a response successfully.
⚠️  HF quota depleted (402). Falling back to Groq...
❌  Groq failed: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01katr34q2erz904dzn297vh2r` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199860, Requested 351. Please try again in 1m31.152s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
🔄 Attempting fallback to 9router ('sragent')...
🔄 Attempting fallback to 9router ('sragent') for LLM response...
✅  9router returned a response successfully.

 68%|██████▊   | 135/200 [01:29<00:24,  2.61it/s]

⚠️  HF quota depleted (402). Falling back to Groq...
❌  Groq failed: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01katr34q2erz904dzn297vh2r` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199828, Requested 5452. Please try again in 38m0.96s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
🔄 Attempting fallback to 9router ('sragent')...
🔄 Attempting fallback to 9router ('sragent') for LLM response...
✅  9router returned a response successfully.
⚠️  HF quota depleted (402). Falling back to Groq...
❌  Groq failed: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01katr34q2erz904dzn297vh2r` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199802, Requested 351. Please try again in 1m6.095999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
🔄 Attempting fallback to 9router ('sragent')...
🔄 Attempting fallback to 9router ('sragent') for LLM response...
✅  9router returned a response successfully.

 68%|██████▊   | 137/200 [01:46<03:59,  3.81s/it]

⚠️  HF quota depleted (402). Falling back to Groq...
❌  Groq failed: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01katr34q2erz904dzn297vh2r` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199787, Requested 5748. Please try again in 39m51.12s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
🔄 Attempting fallback to 9router ('sragent')...
🔄 Attempting fallback to 9router ('sragent') for LLM response...
✅  9router returned a response successfully.
⚠️  HF quota depleted (402). Falling back to Groq...
❌  Groq failed: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01katr34q2erz904dzn297vh2r` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199770, Requested 369. Please try again in 1m0.047999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
🔄 Attempting fallback to 9router ('sragent')...
🔄 Attempting fallback to 9router ('sragent') for LLM response...
✅  9router returned a response successfully.

 73%|███████▎  | 146/200 [02:02<00:40,  1.35it/s]

⚠️  HF quota depleted (402). Falling back to Groq...
❌  Groq failed: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01katr34q2erz904dzn297vh2r` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199751, Requested 5747. Please try again in 39m35.136s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
🔄 Attempting fallback to 9router ('sragent')...
🔄 Attempting fallback to 9router ('sragent') for LLM response...
✅  9router returned a response successfully.
⚠️  HF quota depleted (402). Falling back to Groq...

 89%|████████▉ | 178/200 [03:02<00:08,  2.62it/s]

⚠️  HF quota depleted (402). Falling back to Groq...
❌  Groq failed: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01katr34q2erz904dzn297vh2r` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199964, Requested 5742. Please try again in 41m4.992s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
🔄 Attempting fallback to 9router ('sragent')...
🔄 Attempting fallback to 9router ('sragent') for LLM response...
✅  9router returned a response successfully.
⚠️  HF quota depleted (402). Falling back to Groq...
❌  Groq failed: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01katr34q2erz904dzn297vh2r` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199938, Requested 351. Please try again in 2m4.848s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
🔄 Attempting fallback to 9router ('sragent')...
🔄 Attempting fallback to 9router ('sragent') for LLM response...
✅  9router returned a response successfully.

 92%|█████████▏| 184/200 [03:20<00:18,  1.14s/it]

⚠️  HF quota depleted (402). Falling back to Groq...
❌  Groq failed: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01katr34q2erz904dzn297vh2r` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199925, Requested 5425. Please try again in 38m31.2s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
🔄 Attempting fallback to 9router ('sragent')...
🔄 Attempting fallback to 9router ('sragent') for LLM response...
✅  9router returned a response successfully.
⚠️  HF quota depleted (402). Falling back to Groq...
❌  Groq failed: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01katr34q2erz904dzn297vh2r` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199911, Requested 351. Please try again in 1m53.184s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
🔄 Attempting fallback to 9router ('sragent')...
🔄 Attempting fallback to 9router ('sragent') for LLM response...
✅  9router returned a response successfully.

 99%|█████████▉| 198/200 [03:35<00:00,  2.42it/s]

⚠️  HF quota depleted (402). Falling back to Groq...
❌  Groq failed: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01katr34q2erz904dzn297vh2r` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199889, Requested 5739. Please try again in 40m31.296s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
🔄 Attempting fallback to 9router ('sragent')...
🔄 Attempting fallback to 9router ('sragent') for LLM response...
✅  9router returned a response successfully.
⚠️  HF quota depleted (402). Falling back to Groq...
❌  Groq failed: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-120b` in organization `org_01katr34q2erz904dzn297vh2r` service tier `on_demand` on tokens per day (TPD): Limit 200000, Used 199864, Requested 351. Please try again in 1m32.88s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
🔄 Attempting fallback to 9router ('sragent')...
🔄 Attempting fallback to 9router ('sragent') for LLM response...
✅  9router returned a response successfully.

100%|██████████| 200/200 [03:51<00:00,  1.16s/it]

,row_index,decision_route,provider,fraud_probability,fraud_band,typology,recommended_action,confidence,needs_human_review
0,8564,AUTO_ALLOW,ML_Policy_Engine,0.005556,Low,unknown,allow,0.005556,True
1,26313,AUTO_BLOCK,ML_Policy_Engine,0.992286,Critical,unknown,block,0.992286,False
2,12212,AUTO_BLOCK,ML_Policy_Engine,0.990251,Critical,unknown,block,0.990251,False
3,37578,AUTO_BLOCK,ML_Policy_Engine,0.999821,Critical,unknown,block,0.999821,False
4,21647,AUTO_BLOCK,ML_Policy_Engine,0.991000,Critical,unknown,block,0.991000,False
5,12556,AUTO_BLOCK,ML_Policy_Engine,0.985000,Critical,unknown,block,0.985000,False
6,6887,AUTO_BLOCK,ML_Policy_Engine,0.957698,Critical,unknown,block,0.957698,False
7,45523,AUTO_BLOCK,ML_Policy_Engine,1.000000,Critical,unknown,block,1.000000,False
8,21439,AUTO_BLOCK,ML_Policy_Engine,0.973621,Critical,unknown,block,0.973621,False
9,19165,AUTO_ALLOW,ML_Policy_Engine,0.060833,Low,unknown,allow,0.060833,True
10,19719,AUTO_BLOCK,ML_Policy_Engine,0.996250,Critical,unknown,block,0.996250,False
11,45322,AUTO_BLOCK,ML_Policy_Engine,0.995000,Critical,unknown,block,0.995000,False
12,6689,AUTO_BLOCK,ML_Policy_Engine,0.984825,Critical,unknown,block,0.984825,False
13,23720,AUTO_BLOCK,ML_Policy_Engine,0.869619,Critical,unknown,block,0.869619,False
14,22204,AUTO_BLOCK,ML_Policy_Engine,0.995947,Critical,unknown,block,0.995947,False
15,41373,AUTO_ALLOW,ML_Policy_Engine,0.067980,Low,unknown,allow,0.067980,True
16,37826,AUTO_BLOCK,ML_Policy_Engine,0.990000,Critical,unknown,block,0.990000,False
17,2767,AUTO_ALLOW,ML_Policy_Engine,0.034631,Low,unknown,allow,0.034631,True
18,4347,AUTO_BLOCK,ML_Policy_Engine,0.976060,Critical,unknown,block,0.976060,False
19,22969,AUTO_BLOCK,ML_Policy_Engine,0.978889,Critical,unknown,block,0.978889,False

In [80]:
results_df[available_cols]

,row_index,decision_route,provider,fraud_probability,fraud_band,typology,recommended_action,confidence,needs_human_review
0,8564,AUTO_ALLOW,ML_Policy_Engine,0.005556,Low,unknown,allow,0.005556,True
1,26313,AUTO_BLOCK,ML_Policy_Engine,0.992286,Critical,unknown,block,0.992286,False
2,12212,AUTO_BLOCK,ML_Policy_Engine,0.990251,Critical,unknown,block,0.990251,False
3,37578,AUTO_BLOCK,ML_Policy_Engine,0.999821,Critical,unknown,block,0.999821,False
4,21647,AUTO_BLOCK,ML_Policy_Engine,0.991000,Critical,unknown,block,0.991000,False
...,...,...,...,...,...,...,...,...,...
195,20179,AUTO_ALLOW,ML_Policy_Engine,0.030936,Low,unknown,allow,0.030936,True
196,3792,AUTO_BLOCK,ML_Policy_Engine,0.996000,Critical,unknown,block,0.996000,False
197,18707,AUTO_BLOCK,ML_Policy_Engine,0.929524,Critical,unknown,block,0.929524,False
198,43877,RAG_LLM,9router (sragent),0.727721,Medium,unknown,manual_review,0.500000,True
199,49276,AUTO_BLOCK,ML_Policy_Engine,0.985500,Critical,unknown,block,0.985500,False

## Save the pipeline: RAG config + feature groups + manifest

In [ ]:
import json
from pathlib import Path

BASE_PATH = Path.cwd().parent
#LLM_OUT = BASE_PATH / "database" / "LLM" / "outputs_llm"
#LLM_OUT.mkdir(parents=True, exist_ok=True)

rag_config = {
    "version": "1.0.0",
    "domain": "fraud",
    "created_at": pd.Timestamp.now().isoformat(),

    "system_prompt": FRAUD_SYSTEM_PROMPT,

    "enums": {
        "typologies": ALLOWED_TYPOLOGIES,
        "actions":    ALLOWED_ACTIONS,
    },

    "thresholds": FRAUD_THRESHOLDS,   # auto_allow_below, auto_block_above, k_customers, k_policies

    "llm": {
        "hf_model":   "Qwen/Qwen2.5-Coder-32B-Instruct",
        "groq_model": "openai/gpt-oss-20b",
        "9router_model": "sragent",
        "max_tokens": 512,
        "temperature": 0.2,
    },

    "collections": {
        "fraud_cases": "fraud_cases",
        "legit_cases": "legit_cases",
        "policies":    "fraud_policies",
    },
}

(LLM_OUT / "rag_config.json").write_text(json.dumps(rag_config, indent=2))
print("wrote", LLM_OUT / "rag_config.json")

wrote /Users/miftahhadiyannoor/Documents/credit_risk/data_science/database/LLM/outputs_llm/rag_config.json